### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by moreauxh** [djurodrljaca/tuleap-rest-api-client#15]
Do you recommend a library for unit tests ?

**Comment by djurodrljaca** [comment]
It would probably be best to use python's own unit test framework:
https://docs.python.org/3/library/unittest.html

**Comment by moreauxh** [comment]
I write some test on ArtifactParse. What do you think about using CI ?
Link Travis CI or another one with this project ?

**Comment by djurodrljaca** [comment]
I will take a look at what is needed to configure Travis CI. From what I have seen it should be relatively simple to do...

It would be nice to have something to run on it while I am doing this. Could you prepare at least one unit test in the next day or two?

**Comment by moreauxh** [comment]
wich version of python you are using ? My tests pass to version 2.7 but not for version 3.2 cause by `.clear()` method on `list`

**Comment by djurodrljaca** [comment]
I would say that we need to support these python versions:
- python 2.7
- min version from 3.x that still works with the library
- latest from 3.x
- optionally all 3.x versions that still work with the library

**Comment by djurodrljaca** [comment]
BTW I enabled Travis CI, so hopefully it will work :)

**Comment by djurodrljaca** [comment]
It appears that Travis CI now executes the tests in the pull requests. See https://travis-ci.org/djurodrljaca/tuleap-rest-api-client/builds/250365023
