### ISSUE TITLE
empty table return for link and reverse link using ArtifactParser

### ISSUE THREAD

**Issue by moreauxh** [djurodrljaca/tuleap-rest-api-client#17]
When I do: 
```python
print(artifact.get_links())
print(artifact.get_reverse_links())
```
I have
```
[]
[]
```
The response given by my request is like:
```json
{
    "id": 42,
    "uri": "artifacts/42",
    "xref": "bugs #42",
    "tracker": {
        "id": 6,
        "uri": "trackers/6",
        "label": "Bug"
    },
    "project": {
    "id": 7,
    "uri": "projects/7",
    "label": "MyProject"
    },
    "submitted_by": 7,
    "submitted_by_user": {
        "id": 7,
        "uri": "users/07",
        "user_url": "/users/user1",
        "real_name": "User 1",
        "display_name": "User 1",
        "username": "user1",
        "ldap_id": null,
        "avatar_url": "",
        "is_anonymous": false
    },
    "submitted_on": "2017-05-19T11:46:21+02:00",
    "html_url": "/plugins/tracker/?aid=42",
    "changesets_uri": "artifacts/42/changesets",
    "values": [
        {
            "field_id": 153,
            "type": "string",
            "label": "Summary",
            "value": "Display error on name field"
        },
        {
            "field_id": 166,
            "type": "art_link",
            "label": "Links",
            "links": [
            {
                "id": 101,
                "uri": "artifacts/101",
                "tracker": {
                    "id": 1,
                    "uri": "trackers/1",
                    "label": "Issue"
                    }
            },
            {
                "id": 102,
                "uri": "artifacts/102",
                "tracker": {
                    "id": 1,
                    "uri": "trackers/1",
                    "label": "Issue"
                }
            }
            ],
            "reverse_links": [
            {
                "id": 21,
                "uri": "artifacts/21",
                "tracker": {
                    "id": 7,
                    "uri": "trackers/7",
                    "label": "Bug"
                }
            }
            ]
        },
        {
            "field_id": 142,
            "type": "aid",
            "label": "Artifact ID",
            "value": 42
        }
    ],
    "values_by_field": null,
    "last_modified_date": "2017-05-19T11:46:21+02:00",
    "status": "New",
    "title": "bug1",
    "assignees": []
}
```
I have art_link fields but the parser don't find them.

**Comment by djurodrljaca** [comment]
I took a quick look at the code and I didn't see any obvious bugs in the code...

Could you step through the code with the debugger? This should be the easiest way to find the problem.

**Comment by djurodrljaca** [comment]
BTW could you paste a little more of the code? For example from the ArtifactParser constructor?

I suspect that you didn't set the "link_following" parameter for extracting links.

Probably it would even be a good idea to refactor this class a little. From what I see in the code the "link following" functionality is not actually implemented (at least not correctly). This was done by my coworker some time ago and I suspect that he implemented following the links in the application code, but left this part of the implementation inside the ArtifactParser class...

**Comment by moreauxh** [comment]
I just test with:
```python
if success:
    # SystemEvent
    module = Artifacts(connection)

    success = module.request_artifact(81)

    response = module.get_last_response_message()
    if success:
        response = module.get_data()
    else:
        response = module.get_last_response_message()

    artifact = ArtifactParser(response)

    print(artifact.get_links())
    print(artifact.get_reverse_links())

connection.logout()
```

**Comment by djurodrljaca** [comment]
According to the current implementation you have to set the "link_following" parameter to "All" (to get both links and reverse links) and you also have to set the trackers parameter ... and I am currently not sure exactly to what :)

I will probably take change the implementation of this class so that the "link following" functionality is no longer present, but in the mean time you could try to get it to work with the appropriate parameters in the ArtifactParser constructor...

**Comment by moreauxh** [comment]
```python
if success:

    # SystemEvent
    module = Artifacts(connection)

    success = module.request_artifact(81)

    # Artifact
    response = module.get_last_response_message()
    if success:
        response = module.get_data()
    else:
        response = module.get_last_response_message()

    artifact_response = response

    module = Tracker(connection)

    tracker_list = [23, 8]
    artifact = ArtifactParser(artifact_response, tracker_list, link_following=LinkFollowing.All)

    print(artifact.get_links())
    print(artifact.get_reverse_links())
```
result:
```
[202, 203]
[]
```
If I switch `tracker_list = [23, 8]` by `tracker_list = [8, 23]` I have:
```
[]
[82]
```

**Comment by djurodrljaca** [comment]
I took a look at it again ... yes the implementation of extracting links is a bit messed up. I will also take a look if my coworker forgot to push the changes to this class to github from the project code where the "application code" is located. But in any case this class needs to be fixed...

**Comment by djurodrljaca** [comment]
I ported some of the changes that were not committed yet from our project and refactored the ArtifactParser (I removed tracker_list and link_following parameters and simplified extracting the links).

Please take a look at the code in master and try again.

**Comment by djurodrljaca** [comment]
The last few commits appear to solve this issue. Please close it if you agree.

**Comment by moreauxh** [comment]
Perfect, test added to check this feature.
