### ISSUE TITLE
Create Project e tasks

### ISSUE THREAD

**Issue by aliencrash** [djurodrljaca/tuleap-rest-api-client#2]
Hi.

It's not possible to create projects and tasks?

**Comment by djurodrljaca** [comment]
As far as I know it is not possible to create projects using the REST API, but you should be able to create artifacts (issues, tasks, requirements etc.).

Unfortunately this feature is missing in the current version, but it should be simple to add to [Artifacts.py](https://github.com/djurodrljaca/tuleap-rest-api-client/blob/master/Tuleap/RestClient/Artifacts.py) file, just use the other methods as an example.

You can use https://tuleap.net/api/explorer/ for the documentation and for experimentation.

**Comment by aliencrash** [comment]
Ok thanks.

I got here because may I wil make a integration with Odoo. I need to be able to create a project from Odoo and that also create on tuleap.

**Comment by aliencrash** [comment]
Hi,

Just to update you that I added to the rest api project creation and it
was merged in 9.99.:). Its a base, but later on it will be improved.

Regards

ALIEN GROUP LDA <http://www.alien-group.com> 	

Alaney Dória

CEO | Odoo Consultant

em.alaney.doria@alien-group.com

tm.+244 913 728 600

Linkedin <https://www.linkedin.com/in/alaneyd> Facebook
<http://www.facebook.com/aliengroup> Facebook
<http://www.twitter.com/ohomemeamente>
	Código QR

Rua Doutor Agostinho Neto, 156, Bairro Azul, Luanda - Angola, Tel: +244
913 728 600 | +244 913 728 650,
Website: www.alien-group.com <http://www.alien-group.com>, Email:
geral@alien-group.com <mailto:geral@alien-group.com>

Não imprima este email caso não seja estritamente necessário. A Terra
agradece-lhe!
