### ISSUE TITLE
ModuleNotFoundError: No module named 'Tuleap'

### ISSUE THREAD

**Issue by aliencrash** [djurodrljaca/tuleap-rest-api-client#22]
from Tuleap.RestClient.Connection import Connection, CertificateVerification
ModuleNotFoundError: No module named 'Tuleap'
I'm trying to use the module with Python 3.7, but I'm not able access it after using it in development.

It installs, with easy_install and python but I'm not able to import in production.

**Comment by gbonnefille** [comment]
I'm not Python expert, but I think setup.py needs to declare packages to install.
