### ISSUE TITLE
Project still alive ?

### ISSUE THREAD

**Issue by yannis-rossetto** [djurodrljaca/tuleap-rest-api-client#3]
Hello guys, 

I'm currently writing a StackStorm pack for Tuleap. These packs use python to create the actions the tool can perform. Your library is what I exactly need to ease my pack creation.

So I'm asking you if your project is still alive ? If yes, I can help you by contributing to it if necessary.

Many thanks.

**Comment by djurodrljaca** [comment]
Yes, the project is still alive. If you want I can make you a committer on the project.

**Comment by moreauxh** [comment]
Hello,
I work with Yannis Rossetto on the Tuleap pack, can I help you contributing too ?

**Comment by djurodrljaca** [comment]
Yes, I sent you the invitation.
